config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show, :edit]
  resources :events
  resources :attends, only: [:create, :destroy]
  root 'pages#index'
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  delete '/logout', to: 'sessions#destroy'
  post '/create-event',  to: 'events#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'


  get '/create-event',  to: 'events#new'
  post '/create-event',  to: 'events#create'
  patch '/create-event',  to: 'events#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attend.rb
class Attend < ApplicationRecord
    belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
  validates :attendee_id, presence: true
  validates :attended_event_id, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user, :optional => true
  has_many :passive_attends, class_name: "Attend", foreign_key: "attended_event_id", dependent: :destroy
  has_many :attendees, through: :passive_attends, source: :attendee
end

app/models/user.rb
class User < ApplicationRecord
        has_many :events, dependent: :destroy
    
        has_many :active_attends, class_name: "Attend", foreign_key: "attendee_id", dependent: :destroy
        has_many :attending, through: :active_attends, source: :attended_event
        
        validates :email, presence: true, length: {maximum: 50}, uniqueness: { case_sensitive: false }
        has_secure_password
        validates :password, length: {minimum: 6}, presence: true, on: :create
        validates :password_confirmation, length: {minimum: 6}, on: :create
        validates :password, length: {minimum: 6}, presence: true, on: :update, if: :password_digest_changed?
        validates :password_confirmation, length: {minimum: 6}, on: :update, if: :password_digest_changed?
        
        # Returns the hash digest of the given string.
        def User.digest(string)
          cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
          BCrypt::Password.create(string, cost: cost)
        end
      
        #Adds user to attend list for event
        def attend(event)
          active_attends.create(attended_event_id: event.id)
        end
      
        #Removes a user from the attend list for event
        def unattend(event)
          active_attends.find_by(attended_event_id: event.id).destroy
        end
      
        #Returns true if the current user is attending the event
        def attending?(event)
          attending.include?(event)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper

    private
    
      # Confirms a logged-in user.
      def logged_in_user
        unless current_user
          flash[:danger] = "Please log in."
          redirect_to login_url
        end
      end
    
       # Checks if user is already logged-in
      def already_logged_in?
        if current_user
          redirect_to root_path
        end
      end
    
end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController
  before_action :set_attend, only: [:show, :edit, :update, :destroy]

  # GET /attends
  # GET /attends.json
  def index
    @attends = Attend.all
  end

  # GET /attends/1
  # GET /attends/1.json
  def show
  end

  # GET /attends/new
  def new
    @attend = Attend.new
  end

  # GET /attends/1/edit
  def edit
  end

  # POST /attends
  # POST /attends.json
  def create
    @attend = Attend.new(attend_params)

    respond_to do |format|
      if @attend.save
        format.html { redirect_to @attend, notice: 'Attend was successfully created.' }
        format.json { render :show, status: :created, location: @attend }
      else
        format.html { render :new }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attends/1
  # PATCH/PUT /attends/1.json
  def update
    respond_to do |format|
      if @attend.update(attend_params)
        format.html { redirect_to @attend, notice: 'Attend was successfully updated.' }
        format.json { render :show, status: :ok, location: @attend }
      else
        format.html { render :edit }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attends/1
  # DELETE /attends/1.json
  def destroy
    @attend.destroy
    respond_to do |format|
      format.html { redirect_to attends_url, notice: 'Attend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attend
      @attend = Attend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attend_params
      params.fetch(:attend, {})
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def new
    @event = Event.new
  end 

  def index
    @events =  Event.all
    end

    def create
      @event = current_user.events.build(event_params)
      if @event.save
        current_user.attend(@event)
        flash[:success] = "Event Created"
        redirect_to @event
      else
        
        render :new
      end
    end


    def show
      @event = Event.find(params[:id])
    end 

    def destroy
      @event = Event.find(params[:id])
      authorized?(@event)
      @event.destroy
      flash[:success] = "Event Deleted"
      redirect_to current_user
    end
  
    def attendees
      @event  = Event.find(params[:id])
      @users = @event.attendees.paginate(page: params[:page])
    end
  
  private
  
    def event_params
      params.require(:event).permit(:place, :description, :date)
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def index
end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :already_logged_in?, only: [:new, :create]

  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		redirect_to user
  	else
      flash.now[:danger] = 'Invalid Email or Password'
  		render :new
  	end
  end

  def destroy
  	log_out
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_logged_in?, only: [:new, :create]

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		log_in @user
  		redirect_to @user
  	else
  		render :new
  	end
  end

  def show
  	@user = User.find(params[:id])

    if current_user && @user.id == current_user.id
      @display_email = "Your"
    end 
  end 





  private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attends_helper.rb
module AttendsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the user.
    def log_in(user)
      session[:user_id] = user.id
    end
  
    # Returns current user (if any)
    def current_user
      if user_id = session[:user_id]
        @current_user = User.find(user_id)
      end
    end
  
    # Logs out the current user
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attends/_form.html.erb
<%= form_with(model: attend, local: true) do |form| %>
  <% if attend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attend.errors.count, "error") %> prohibited this attend from being saved:</h2>

      <ul>
      <% attend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attends/edit.html.erb
<h1>Editing Attend</h1>

<%= render 'form', attend: @attend %>

<%= link_to 'Show', @attend %> |
<%= link_to 'Back', attends_path %>

app/views/attends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attends</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attends.each do |attend| %>
      <tr>
        <td><%= link_to 'Show', attend %></td>
        <td><%= link_to 'Edit', edit_attend_path(attend) %></td>
        <td><%= link_to 'Destroy', attend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attend', new_attend_path %>

app/views/attends/new.html.erb
<h1>New Attend</h1>

<%= render 'form', attend: @attend %>

<%= link_to 'Back', attends_path %>

app/views/attends/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_attend_path(@attend) %> |
<%= link_to 'Back', attends_path %>

app/views/events/_event_form.html.erb
    <%= form_for(@event, url: url, html: { multipart: true }) do |f| %>  
 <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <%= f.label :place, "Place"%><span id="required">*</span>
          <%= f.text_field :place, class: "form-control" %>
          <p class="help-block"></p>
        </div> 
      </div> 

      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <%= f.label :description, "Description" %><span id="required">*</span>
          <%= f.text_area :description, style: "resize: none;", rows: "10", class: "form-control" %>
          <p class="help-block"></p>
        </div>
      </div>

    


      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <%= f.label :date, "Date" %><span id="required">*</span><br>
          <%= f.datetime_select :date, options = {ampm: true, minute_step: 15, start_year: Date.today.year, end_year: Date.today.year + 5, order: [:month, :day, :year], default: Time.now} %>
          <p class="help-block"></p>
        </div>
      </div>

    

      <%= f.submit button, class: "btn btn-primary", style: "margin-top: 30px;" %>
    <% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
 
 <% provide(:place, "All Events") %>   
  <div class="container text-center">
    <div class="row">
      <h1>Les événements</h1>
    </div> 
     <p> <% if current_user %>
            <li><%= link_to "Créer votre événement", create_event_path, button: "Create Event" %></li>
            </p>
  </div>
        
                <% @events.each do |event|%>
<h2><%= event.place%></h2>
<p><%= event.description%></p>
<p><%= event.date%></p>



<%end%>
<%end%>

app/views/events/new.html.erb
 <% provide(:title, "Create Event") %> 
  
  <div class="container text-center">
    <div class="row">
      <h3>Create an Event</h3>
      <hr> 
    </div> 
    <%= render "event_form", url: create_event_path, button: "Create Event" %>
  </div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!-- Nav-Bar -->
  <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-expand-lg">
      </div>
      <div class="navbar-expand-lg">
        <ul class="nav navbar-expand-lg">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Events", events_path %></li>
          <% if current_user %>
            <li><%= link_to "Create Event", create_event_path %></li>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Logout", logout_path, method: "delete" %></li>
          <% else %>                
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Bienvenu sur notre Eventbrite</h1>

<p><%= link_to "Login", login_path %></p>

app/views/users/_user_form.html.erb
<%= form_for(@user, url: url) do |f| %>
      
      

      <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
          <%= f.label :email %><br>
          <%= f.email_field :email, class: "form-control" %><br>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
          <%= f.label :password %><br>
          <%= f.password_field :password, class: "form-control" %><br>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
          <%= f.label :password_confirmation, "Password Confirmation" %><br>
          <%= f.password_field :password_confirmation, class: "form-control" %><br>
        </div>
      </div>

      <%= f.submit button_text, class: "btn btn-primary" %><br><br>
    <% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
 <% provide(:title, "Sign Up") %>

  <!-- Page Content -->
  <div class="container text-center">
    <div class="row">
      <h3>Sign Up</h3>
      (All fields are required)
      <hr>
    </div>
    <%= render "user_form", url: signup_path, button_text: "Sign Up" %>
  </div>

app/views/users/show.html.erb
  <% provide(:title, "#{@display_email} Profile") %>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-md-offset-3 text-center">
        <h1><%= @display_email  %> Profile</h1>
        <h2> <%= current_user.email %><h2>
        <h3><li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Events", events_path %></li>
          </h3>
      </div>
      <p> <% if current_user %>
            <li><%= link_to "Logout", logout_path, method: "delete" %></li>
            </p>
                      <% end %>

    </div>
  </div>